/**
 * Re-stamp the `bundleVersion` of every fixture bundle to the value computed
 * from THIS checkout's schema.
 *
 * Why: `bundleVersion` is a contract hash derived from the schema
 * (see ./src/schema.ts). This fork's self-hosting patches change the schema, so
 * the hash differs from upstream's — but the committed fixtures under
 * `fixtures/*` are generated by upstream and carry upstream's value. That makes
 * `fixtures.test.ts` fail on every fork build. Rather than re-sync fixtures
 * against a builder (needs infra), we deterministically overwrite just the
 * `bundleVersion` field. The fixture data still parses under the fork schema
 * (the test's `publishedProjectBundle.parse` keeps guarding that), so only the
 * stamp needs refreshing.
 *
 * Usage:
 *   pnpm fixtures:restamp          # rewrite stale stamps in place
 *   pnpm fixtures:restamp --check  # report drift and exit non-zero (CI)
 *
 * The rewrite is a surgical text replace of the `bundleVersion` value only, so
 * the rest of each data.json keeps its exact (oxfmt) formatting.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { bundleVersion } from "../src/schema";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const fixturesRoot = resolve(scriptDir, "../../../fixtures");
const check = process.argv.includes("--check");

const target = JSON.stringify(bundleVersion);
const pattern = /("bundleVersion"\s*:\s*)("[^"]*"|\d+)/;

let drift = 0;
let updated = 0;

for (const entry of readdirSync(fixturesRoot, { withFileTypes: true })) {
  if (entry.isDirectory() === false) {
    continue;
  }
  const file = join(fixturesRoot, entry.name, ".webstudio", "data.json");
  if (existsSync(file) === false) {
    continue;
  }
  const text = readFileSync(file, "utf8");
  const match = text.match(pattern);
  if (match === null) {
    continue;
  }
  if (match[2] === target) {
    continue;
  }
  drift += 1;
  if (check) {
    console.error(`drift: ${entry.name} has ${match[2]}, expected ${target}`);
    continue;
  }
  writeFileSync(file, text.replace(pattern, `$1${target}`));
  updated += 1;
  console.info(`re-stamped ${entry.name} → ${target}`);
}

if (check) {
  if (drift > 0) {
    console.error(
      `${drift} fixture bundle(s) out of date. Run: pnpm fixtures:restamp`
    );
    process.exit(1);
  }
  console.info(`fixtures bundleVersion up to date (${target})`);
} else {
  console.info(
    updated === 0
      ? `fixtures already current (${target})`
      : `re-stamped ${updated} fixture bundle(s) → ${target}`
  );
}
